# -*- coding: utf-8 -*-
"""Rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFs3jbgZv06rKkfRY7ElYpE7xVOHXNxT
"""

!pip install  langchain langchain-core langchain-groq langchain-community sentence_transformers langchain_text_splitters pypdf chromadb faiss-cpu langchain_huggingface

from langchain_groq import ChatGroq
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
from langchain_community.embeddings import HuggingFaceEmbeddings

text_data = PyPDFLoader('/content/Psychology_Complete_Short_Guide.pdf').load()

for i in text_data:
  i.metadata['source'] = 'Psychology_Complete_Short_Guide'

splitter = RecursiveCharacterTextSplitter(chunk_size=350,chunk_overlap=50)

chunks = splitter.split_documents(text_data)

len(chunks)

from langchain_huggingface import HuggingFaceEmbeddings

# This model is 1024 dimensions.
model_name = "BAAI/bge-m3"

print(f"Downloading {model_name}... this may take a minute.")
embedd_model = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs={'device': 'cpu'} # Use 'cuda' if you have a GPU
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(chunks, embedd_model)

vectorstore.save_local("rag_vector_db")

answer = [doc.page_content for doc in vectorstore.similarity_search("Foundations of Psychology",k=3)]

print(answer)

llm = ChatGroq(groq_api_key="paste_here_api",model="llama-3.1-8b-instant")

def rag():
    quiery = input("Enter Your Quiry")

    context_sematic = vectorstore.similarity_search(quiery,k=4)

    context_sematic = [i.page_content for i in context_sematic]

    context = "\n".join(context_sematic)
    prompt = f"""
    You are an intelligent RAG assistant.

    User Query:
    {quiery}

    Retrieved Context:
    {context}

    Instructions:
    1. Carefully understand the user's query.
    2. Use ONLY the retrieved context to generate the answer.
    3. If the context contains the answer, respond clearly, accurately, and naturally.
    4. If multiple relevant points exist, combine them into one well-structured response.
    5. If the context does not contain enough information, say:
      "I couldn't find enough relevant information in the provided document."
    6. Do not make up facts or use outside knowledge.
    7. Keep the response concise but helpful.
    8. If the user asks for steps, explain in numbered format.
    9. If the user asks for comparison, use table format when useful.

    Final Answer:
    """
    print(llm.invoke(prompt).content)

rag()

vectorstore.save_local("faiss_memory")

